# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
env:
  TZ: Asia/Shanghai

on:
  schedule:
    - cron: 21 2 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run with python@v3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: git config --global user.email "johnsonlee1126@163.com"
    - run: git config --global user.name "Johnson"
    - run: python main.py
